/**
 * ASTRA Report Extractor v3 — ESM script using pdfjs-dist legacy build
 * Run: node --experimental-vm-modules scripts/extract-reports.mjs
 */

import { readFileSync, writeFileSync, statSync, readdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { createRequire } from 'module';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPORTS_DIR = 'A:\\Astra last year reports';
const OUTPUT_FILE = join(__dirname, '..', 'src', 'astraKnowledge.ts');

// Dynamically import pdfjs-dist legacy ESM build
const pdfjsLib = await import('../node_modules/pdfjs-dist/legacy/build/pdf.mjs');
// Point to the worker file (required even in Node.js)
const workerPath = new URL('../node_modules/pdfjs-dist/legacy/build/pdf.worker.mjs', import.meta.url).href;
pdfjsLib.GlobalWorkerOptions.workerSrc = workerPath;

function getDocLabel(filename) {
  const f = filename.toLowerCase();
  if (f.includes('project')) return 'Project Report (SEVC 2025)';
  if (f.includes('cost')) return 'Cost Report (SEVC 2026)';
  if (f.includes('design')) return 'Design Report (SEVC 2026)';
  if (f.includes('innovation')) return 'Innovation Report (SEVC 2026)';
  if (f.includes('virtual') || f.includes('presentation')) return 'Virtual Presentation / Report (SEVC 2026)';
  return 'General Report';
}

function cleanText(text) {
  return text
    .replace(/\r\n/g, '\n')
    .replace(/\n{3,}/g, '\n\n')
    .replace(/[^\x20-\x7E\n]/g, ' ')
    .replace(/ {3,}/g, ' ')
    .trim();
}

async function extractText(filePath) {
  const data = new Uint8Array(readFileSync(filePath));
  const loadingTask = pdfjsLib.getDocument({ data, disableWorker: true, verbosity: 0 });
  const doc = await loadingTask.promise;

  let fullText = '';
  for (let i = 1; i <= doc.numPages; i++) {
    try {
      const page = await doc.getPage(i);
      const content = await page.getTextContent();
      const pageText = content.items.map(item => item.str || '').join(' ');
      fullText += pageText + '\n';
    } catch (_) { /* skip bad pages */ }
  }
  return { text: cleanText(fullText), pages: doc.numPages };
}

async function main() {
  const files = readdirSync(REPORTS_DIR).filter(f => f.endsWith('.pdf'));
  console.log(`\nFound ${files.length} PDFs in: ${REPORTS_DIR}\n`);

  const knowledgeDocs = [];

  for (const file of files) {
    const filePath = join(REPORTS_DIR, file);
    const label = getDocLabel(file);
    const sizeMB = (statSync(filePath).size / 1024 / 1024).toFixed(2);
    console.log(`Processing: ${file} (${sizeMB}MB) — ${label}`);

    try {
      const { text, pages } = await extractText(filePath);
      const words = text.split(/\s+/).filter(Boolean).length;
      const cappedText = text.slice(0, 10000);
      console.log(`  ✓ ${pages} pages | ${words} words extracted`);
      knowledgeDocs.push({ label, filename: file, pages, text: cappedText });
    } catch (err) {
      console.warn(`  ✗ Failed: ${err.message}`);
      knowledgeDocs.push({ label, filename: file, pages: 0, text: `[Could not extract: ${file}]` });
    }
  }

  const totalWords = knowledgeDocs.reduce((s, d) => s + d.text.split(/\s+/).filter(Boolean).length, 0);

  const tsContent = `// ─────────────────────────────────────────────────────────────────────────────
// AUTO-GENERATED by scripts/extract-reports.mjs
// ASTRA Team Historical Knowledge Base — Extracted from official PDF reports
// Source: A:\\Astra last year reports (${files.length} documents, ~${totalWords} words)
// Generated: ${new Date().toISOString()}
//
// ✅ Firebase Storage used: 0 MB — embedded directly in the app bundle
// ✅ The AI uses this as CONTEXT (not training weights) to answer questions
//    about Team ASTRA's past solar car engineering work, designs, costs etc.
// ─────────────────────────────────────────────────────────────────────────────

export interface AstraDocument {
  label: string;
  filename: string;
  pages: number;
  text: string;
}

export const ASTRA_KNOWLEDGE_BASE: AstraDocument[] = ${JSON.stringify(knowledgeDocs, null, 2)};

/**
 * Build a full context prompt string for the AI assistant.
 * maxCharsPerDoc controls how much of each doc is included.
 */
export function buildAstraContext(maxCharsPerDoc = 2000): string {
  const validDocs = ASTRA_KNOWLEDGE_BASE.filter(d => !d.text.startsWith('['));
  if (validDocs.length === 0) return '';
  return [
    'TEAM ASTRA HISTORICAL KNOWLEDGE BASE:',
    'The following content is extracted from Team ASTRA\\'s official engineering reports submitted for SEVC 2025 and SEVC 2026 solar car competitions.',
    'Use this knowledge to answer any questions about the team\\'s past work, design decisions, costs, innovations, and progress.',
    '',
    ...validDocs.map(doc =>
      \`=== \${doc.label} (\${doc.pages} pages) ===\\n\${doc.text.slice(0, maxCharsPerDoc)}\`
    )
  ].join('\\n\\n');
}

/**
 * Smart search — returns the most relevant document sections for a given query.
 * Uses simple keyword frequency scoring.
 */
export function searchKnowledge(query: string, maxResults = 3): AstraDocument[] {
  const terms = query.toLowerCase().split(/\\s+/).filter(t => t.length > 3);
  return ASTRA_KNOWLEDGE_BASE
    .map(doc => {
      const lowerText = doc.text.toLowerCase();
      const score = terms.reduce((sum, term) => {
        const matches = lowerText.match(new RegExp(term, 'g'));
        return sum + (matches ? matches.length : 0);
      }, 0);
      return { ...doc, _score: score };
    })
    .filter(d => d._score > 0)
    .sort((a, b) => b._score - a._score)
    .slice(0, maxResults)
    .map(({ _score, ...doc }) => doc);
}
`;

  writeFileSync(OUTPUT_FILE, tsContent, 'utf8');
  const sizeKB = (statSync(OUTPUT_FILE).size / 1024).toFixed(1);

  console.log('\n' + '='.repeat(60));
  console.log(`✅ Knowledge base: src/astraKnowledge.ts (${sizeKB} KB)`);
  console.log(`   Documents: ${knowledgeDocs.length} | Words: ${totalWords}`);
  console.log(`   Firebase Storage used: 0 MB ✓`);
  console.log('='.repeat(60) + '\n');
}

main().catch(err => {
  console.error('Fatal:', err);
  process.exit(1);
});
