/**
 * ASTRA Report Extractor v2 — uses pdfjs-dist (Node-compatible legacy build)
 * Extracts text from all PDFs in A:\Astra last year reports
 * Writes the result to src/astraKnowledge.ts (NO Firebase storage used)
 */

const fs = require('fs');
const path = require('path');

const REPORTS_DIR = 'A:\\Astra last year reports';
const OUTPUT_FILE = path.join(__dirname, '..', 'src', 'astraKnowledge.ts');

function getDocLabel(filename) {
  const f = filename.toLowerCase();
  if (f.includes('project')) return 'Project Report (SEVC 2025)';
  if (f.includes('cost')) return 'Cost Report (SEVC 2026)';
  if (f.includes('design')) return 'Design Report (SEVC 2026)';
  if (f.includes('innovation')) return 'Innovation Report (SEVC 2026)';
  if (f.includes('virtual') || f.includes('presentation')) return 'Virtual Presentation / Report (SEVC 2026)';
  return 'General Report';
}

function cleanText(text) {
  return text
    .replace(/\r\n/g, '\n')
    .replace(/\n{3,}/g, '\n\n')
    .replace(/[^\x20-\x7E\n]/g, ' ')
    .replace(/ {3,}/g, ' ')
    .trim();
}

async function extractPDF(filePath) {
  // Use pdfjs-dist legacy build (works in Node.js without canvas)
  const pdfjsLib = require('pdfjs-dist/legacy/build/pdf.js');
  pdfjsLib.GlobalWorkerOptions.workerSrc = false; // disable worker in Node

  const data = new Uint8Array(fs.readFileSync(filePath));
  const doc = await pdfjsLib.getDocument({ data, disableWorker: true }).promise;

  let fullText = '';
  for (let i = 1; i <= doc.numPages; i++) {
    const page = await doc.getPage(i);
    const content = await page.getTextContent();
    const pageText = content.items.map(item => item.str).join(' ');
    fullText += pageText + '\n';
  }
  return { text: cleanText(fullText), pages: doc.numPages };
}

async function main() {
  const files = fs.readdirSync(REPORTS_DIR).filter(f => f.endsWith('.pdf'));
  console.log(`\nFound ${files.length} PDF files in ${REPORTS_DIR}\n`);

  const knowledgeDocs = [];

  for (const file of files) {
    const filePath = path.join(REPORTS_DIR, file);
    const label = getDocLabel(file);
    const sizeMB = (fs.statSync(filePath).size / 1024 / 1024).toFixed(2);
    console.log(`Processing: ${file} (${sizeMB}MB) — ${label}`);

    try {
      const { text, pages } = await extractPDF(filePath);
      const words = text.split(/\s+/).length;
      // Cap each document to keep bundle manageable but useful
      const cappedText = text.slice(0, 10000);
      console.log(`  ✓ ${pages} pages, ${words} words extracted`);
      knowledgeDocs.push({ label, filename: file, pages, text: cappedText });
    } catch (err) {
      console.warn(`  ✗ Could not parse: ${err.message}`);
      knowledgeDocs.push({ label, filename: file, pages: 0, text: `[PDF could not be parsed: ${file}]` });
    }
  }

  const tsContent = `// ─────────────────────────────────────────────────────────────────────────────
// AUTO-GENERATED by scripts/extract-reports.cjs
// ASTRA Team Historical Knowledge Base — Extracted from PDF reports
// Source: A:\\Astra last year reports (${files.length} documents)
// Generated: ${new Date().toISOString()}
//
// ✅ Firebase Storage used: 0 MB
// ✅ This data is embedded into the app bundle — no external uploads needed
// ✅ The AI uses this as CONTEXT (not "training") — it reads this to answer
//    questions about Team ASTRA's past engineering work
// ─────────────────────────────────────────────────────────────────────────────

export interface AstraDocument {
  label: string;
  filename: string;
  pages: number;
  text: string;
}

export const ASTRA_KNOWLEDGE_BASE: AstraDocument[] = ${JSON.stringify(knowledgeDocs, null, 2)};

/**
 * Returns a context string for the AI assistant.
 * Pass maxCharsPerDoc to limit token usage.
 */
export function buildAstraContext(maxCharsPerDoc = 2000): string {
  const docs = ASTRA_KNOWLEDGE_BASE.filter(d => d.text && !d.text.startsWith('['));
  if (docs.length === 0) return '';
  return [
    'TEAM ASTRA HISTORICAL KNOWLEDGE BASE:',
    'The following is extracted from Team ASTRA\\'s official engineering reports for SEVC 2025 & 2026.',
    '',
    ...docs.map(doc =>
      \`=== \${doc.label} (\${doc.pages} pages) ===\\n\${doc.text.slice(0, maxCharsPerDoc)}\`
    )
  ].join('\\n\\n');
}

/**
 * Smart search — finds the most relevant document sections for a query.
 */
export function searchKnowledge(query: string, maxResults = 3): AstraDocument[] {
  const terms = query.toLowerCase().split(/\\s+/).filter(t => t.length > 3);
  return ASTRA_KNOWLEDGE_BASE
    .map(doc => {
      const lowerText = doc.text.toLowerCase();
      const score = terms.reduce((sum, term) => {
        return sum + (lowerText.match(new RegExp(term, 'g')) || []).length;
      }, 0);
      return { ...doc, score };
    })
    .filter(d => (d as any).score > 0)
    .sort((a, b) => (b as any).score - (a as any).score)
    .slice(0, maxResults);
}
`;

  fs.writeFileSync(OUTPUT_FILE, tsContent, 'utf8');
  const sizeKB = (fs.statSync(OUTPUT_FILE).size / 1024).toFixed(1);
  const totalWords = knowledgeDocs.reduce((s, d) => s + d.text.split(/\s+/).length, 0);

  console.log('\n' + '='.repeat(60));
  console.log(`✅ Knowledge base written: src/astraKnowledge.ts`);
  console.log(`   Size: ${sizeKB} KB | Documents: ${knowledgeDocs.length} | Total words: ${totalWords}`);
  console.log(`   Firebase Storage used: 0 MB ✓`);
  console.log('='.repeat(60));
}

main().catch(err => {
  console.error('Fatal:', err);
  process.exit(1);
});
